### PR TITLE
Detect an explicit super method call outside its corresponding override

### LINKED ISSUE #6: Prohibit calling a super method from a method other than its overridden method
Calling super methods that have side effects (like many android lifecycle methods) multiple times can lead to hard to track down bugs. 

```
 Caused by: java.lang.IllegalStateException: SavedStateRegistry was already restored.
    at androidx.savedstate.SavedStateRegistry.performRestore(SavedStateRegistry.java:191)
    at androidx.savedstate.SavedStateRegistryController.performRestore(SavedStateRegistryController.java:62)
    at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:321)
    at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
```

Usually it is a good idea to only explicitly call a super method from a method overriding that method. e.g.

```java
	@Override
	protected void onCreate(Bundle savedInstanceState)
	{
	        super.onCreate(savedInstanceState);
	        // ...
	}
```

And avoid calling it transitively, like

```java
	@Override
	protected void onCreate(Bundle savedInstanceState)
	{
	        setTheme();
	        // ...
	}

        private void setTheme() {
                super.onCreate(savedInstanceState);
        }
```

### PR DESCRIPTION
**Pull request by jzbrooks**
Resolves #6

### CODE REVIEW

File: checks/src/main/kotlin/com/faithlife/lint/SkippedClassLocalOverrideDetector.kt [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+import org.jetbrains.uast.UCallExpression
+import org.jetbrains.uast.getContainingUClass
+import org.jetbrains.uast.getContainingUMethod
+
+class SkippedClassLocalOverrideDetector : Detector(), SourceCodeScanner {
+    override fun getApplicableUastTypes() = listOf(UCallExpression::class.java)
+
+    override fun createUastHandler(context: JavaContext) = object : UElementHandler() {
+        override fun visitCallExpression(node: UCallExpression) {
+            val method = checkNotNull(node.resolve()) { "A call expression must resolve to a method." }
```
Comment (jzbrooks) [inline checks/src/main/kotlin/com/faithlife/lint/SkippedClassLocalOverrideDetector.kt]: Would a lambda that's immediately invoked cause a crash here?

Comment (jzbrooks) [reply checks/src/main/kotlin/com/faithlife/lint/SkippedClassLocalOverrideDetector.kt]: Lambdas still resolve, but other call types like java array initializers don't. So this is problematic as is. 2b88f6220da95178b14659503bb2c80cca7e9a67 should address it.
